In [4]:
import xlwings as xw
import yfinance as yf
import datetime as dt
import pandas as pd

In [5]:
tickers = ['AAPL', 'MSFT', 'F', 'O', 'BND', 'KO', 'JPM']

In [6]:
# creating a defined function for importing stock data
def import_securities_data(securities_tickers, enter_time_amount, enter_time_type):

    # time delta method function doesnt take the following date time types, it only takes in days. so we convert the respective time types into days by doing some quick math for the user to convert into days
    other_times_types = ['y', 'Y',  'm', 'M', 'w', 'W']
    
    month_type = ['m', 'M']

    week_type = ['w', 'W']

    year_type = ['y', 'Y']

    # if statement that allows us to make a conditional statement to see if the user has inputted any of the time types listed under the other_times_types variable. if so is the case it moves on to the follwing if conditional statements and executes the respective function under the if statenebt that the conditional value was true
    if enter_time_type in other_times_types:
        
        if enter_time_type in month_type: 
            
            enter_time_amount = 30 * enter_time_amount

        elif enter_time_type in week_type:

            enter_time_amount = 7 * enter_time_amount
        
        elif enter_time_type in year_type:

            enter_time_amount = 365 * enter_time_amount

    
    # create a variable to assign the end date and start dates of the data that we want to dowload, the start date is dynamic and customizable to the user's preference of the data one want to download
    # credit to John Droescher for this part of the code
    start_date = dt.datetime.today() - pd.Timedelta(enter_time_amount, "d")
    end_date = dt.datetime.today()
    
    # this returns all of the securities related historical data utilizing yahoo finance's API
    return yf.download(start= start_date, end= end_date, tickers= securities_tickers)

In [13]:
equity_portfolio = import_securities_data(tickers, 1, "y")

equity_portfolio = equity_portfolio['Adj Close']

equity_portfolio

[*********************100%%**********************]  7 of 7 completed

Ticker,AAPL,BND,F,JPM,KO,MSFT,O
Date,,,,,,,
2023-02-21,147.691666,69.645592,11.428380,135.752777,57.971054,250.613144,61.790966
2023-02-22,148.119370,69.800552,11.437747,134.712463,58.145550,249.462585,62.075191
2023-02-23,148.606766,70.052361,11.306602,135.791656,58.252186,252.696045,62.605762
2023-02-24,145.931061,69.664955,11.128619,137.016663,58.009830,247.191238,61.563595
2023-02-27,147.134628,69.781174,11.297235,138.212524,57.990440,248.123581,61.355160
...,...,...,...,...,...,...,...
2024-02-12,187.149994,72.389999,12.638965,175.789993,59.700001,414.493500,52.669998
2024-02-13,185.039993,71.760002,12.346848,174.259995,59.349998,405.570007,51.520000
2024-02-14,184.149994,72.029999,12.230000,176.029999,59.290001,409.489990,51.389999
2024-02-15,183.860001,72.230003,12.520000,179.869995,59.400002,406.559998,52.020000
2024-02-16,182.309998,72.000000,12.300000,179.029999,59.389999,404.059998,52.330002

In [24]:
wk = xw.books.open('/Users/stevenfernandez/Library/CloudStorage/OneDrive-TheCityCollegeofNewYork/Intro to VBA.xlsm')

sheet = wk.sheets('Sheet1')

sheet['A1'].value = equity_portfolio

sheet['A1:C3'].options(pd.DataFrame).value

                  AAPL        BND
Date
2023-02-21  147.691666  69.645592
2023-02-22  148.119370  69.800552

In [23]:
#students will need this for setting the file path towards the excel file they are working with. they would need this if they have their files saved in OneDrive
import os

# Define the value of the environment variable
onedrive_path = os.path.expanduser("~/OneDrive-TheCityCollegeofNewYork")

# Set the environment variable
os.environ['ONEDRIVE_COMMERCIAL_MAC'] = onedrive_path

# Verify that the environment variable is set
print("ONEDRIVE_COMMERCIAL_MAC set to:", os.getenv('ONEDRIVE_COMMERCIAL_MAC'))

ONEDRIVE_COMMERCIAL_MAC set to: /Users/stevenfernandez/OneDrive-TheCityCollegeofNewYork